logging:
  level:
    com:
      geo:
        security: info
    org:
      hibernate:
        SQL: info
      quartz: info
    root: info
  path: logs
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
  servlet:
    context-path: /SpringGeolocation
  ssl:
    enabled: false
    key-alias: geolocation
    key-password: PRIYANKA
    key-store: classpath:server.jks
    key-store-password: PRIYANKA
    key-store-provider: SUN
    key-store-type: JKS
spring:
  aop:
    proxy-target-class: false
  datasource:
    continue-on-error: true
    data: classpath:data-mysql.sql
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: 'always'
    password: root
    platform: mysql
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://localhost:3306/googlemap
    username: root
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    password: pintu@12345
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 50000
          starttls:
            enable: true
            required: true
          timeout: 30000
          writetimeout: 5000
    protocol: smtp
    test-connection: false
    username: niranjanpanigrahi20099@gmail.com
  quartz:
    jdbc:
      comment-prefix: '--******** '
      initialize-schema: always
    job-store-type: 'jdbc'
welcome:
  message: Hello World
  
  
  spring:
  application:
    name: SpringGeolocation
  cache:
    jcache:
      config: classpath:ehcache.xml
  cache-names: Address


